Remove any chance of incorrect score handling due to missing entries in `score_process_queue`
ppy/osu-queue-score-statistics pull request #175
Opened 2023-12-04 10:03 UTC by peppy

While working through the import process today to ensure we have everything covered, I realised that the previous fix I made for  ensuring scores are processed was insufficient due to the `null` allowance. Because score submission in web-10 is not done within a transaction, there's a window of time where rows are in `osu_scores_high` but not in `score_process_queue`.

To resolve this, we need to assume two modes of operation:

- Batch processing, when `StartId` is non-null, which will now process from the specified ID up to the last entry in `osu_scores_high` which doesn't have a `score_process_queue` entry (generally two days before current time, due to partition cycling).
- Live mode, when `StartId` is null, which will now process only entries with a `score_process_queue` entry.

I haven't tested this yet, PRing for feedback in the mean time.

2023-12-04 10:46 UTC, bdach requested changes
Not sure I know about enough about the tables / osu-web-10 to provide a meaningful review on that front but ---

2023-12-04 13:04 UTC, peppy commented on osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
> +                where = "WHERE score_id >= @lastId AND score_id <= @";
Your guess is as good as mine as to how this happened.

2023-12-05 07:15 UTC, bdach approved these changes
looks better in theory

2023-12-07 00:09 UTC, smoogipoo commented
Just so I understand, I basically need to now specify `--start-id=0` every time I need to do processing? i.e. https://github.com/smoogipoo/diffcalc-sheet-generator/blob/170990b323cb421e0a969d14c3a6ee3730858abc/docker/importer/start.sh#L29-L38

2023-12-07 02:34 UTC, peppy commented
> Just so I understand, I basically need to now specify `--start-id=0` every time I need to do processing?

Yep, and remove `exit-on-completion`.

2023-12-07 09:25 UTC, merged